### ISSUE TITLE
Test Issue : Choosing the tech stack

### ISSUE THREAD

**Issue by q1an-w** [q1an-w/soen341-project#1]
testing out github issues but at the same time well choose a tech stack

**Comment by im-samwong** [comment]
In terms of database, I just looked into MongoDB and I believe it would be good to use since we should all be familiar with JSON and it is not necessary to have structured database since the relations between our users and etc. are not that in depth.

**Comment by q1an-w** [comment]
In terms of frontend I think React is good since it has an easy entry level so even people who haven't used it before should pick it up quickly

**Comment by im-samwong** [comment]
So for now I'm thinking:
- HTML
- CSS
- JSX
- Bootstrap 5
- JavaScript
- MongoDB
- ReactJS
- NodeJS
- ExpressJS
